### ISSUE TITLE
add the possibility to show the current issue open 

### ISSUE THREAD

**Issue by yoyomax80400** [youdroid/home-assistant-gitea#2]
Hi, 
Thanks for this add-on,
Could you please add a sensor to view the open issue like : 
status         title
open.          issue for add nothing 

Thanks

**Comment by youdroid** [comment]
Hi !
Thank you for your support.
Yes I can. I will add the total number of issues. And for only the last issue add its link and state and title.
Is it ok for you?

**Comment by yoyomax80400** [comment]
Hi, 
Yes you can make a counter for the total issue 
But if possible, I will be happy to see all issue in list with the status and the title ( the link if possible is a plus ) 

Thanks

**Comment by youdroid** [comment]
Ok, in addition to adding the information on the last issue, I will create a list containing all the issues with their information.

I should be done soon 👍

**Comment by youdroid** [comment]
@yoyomax80400, it's implemented, I think you can get the latest release and test this new feature 😁

**Comment by yoyomax80400** [comment]
Thanks for make the change quickly, 
Could please provide a exemple to parse the json to a card or custom card in home assistante ? 

Thanks your so much
